services:
  keycloak_demo:
    image: quay.io/keycloak/keycloak:22.0
    command: ["start-dev"]
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres_keycloak_demo
      KC_DB_URL_DATABASE: keycloak
      KC_DB_PASSWORD: password
      KC_DB_USERNAME: keycloak
      KC_DB_SCHEMA: public
      KEYCLOAK_ADMIN: ayoub
      KEYCLOAK_ADMIN_PASSWORD: ayoub
    ports:
      - "8080:8080"
    depends_on:
      postgres_keycloak_demo:
        condition: service_healthy
    networks:
      - keycloak_network

  postgres_keycloak_demo:
    image: postgres:14.2
    command: ["postgres", "-c", "max_connections=200"]
    volumes:
      - pgdata_keycloak_demo:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "keycloak"]
    ports:
      - "5432:5432"
    networks:
      - keycloak_network
volumes:
  pgdata_keycloak_demo:
networks:
  keycloak_network:
    driver: bridge

